### ISSUE TITLE
Enhancement request

### ISSUE THREAD

**Issue by lionelmace** [lgrateau/odm-ondocker#1]
- rename the repo in lowercase to be able to use the name in the build script

- ability to git clone the repo directly in ODM_INSTALL instead of the .zip
   >> change the script to replace docker-compose by odm-ondocker

- in docker-compose.yml add the image tag to name the docker image. Because by default, it creates dockercompose-decisioncenter.
`version: '2'
services:
  dbserver:
    build: 
        context: ./
        dockerfile: ./derby-server-db/Dockerfile
    image: odm-dbserver:8.8.1.1
    ports:
    - 1527:1527
    environment:
    - SAMPLE=true

  decisionserverconsole:
    build: 
      context: ../
      dockerfile: ./docker-compose/decisionserverconsole/Dockerfile
    image: odm-decisionserverconsole:8.8.1.1
    links:
    - dbserver
    depends_on:
    - dbserver
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    ports:
    - 9080:9080
    - 1883:1883

  decisionrunner:
    build: 
      context: ../
      dockerfile: ./docker-compose/decisionrunner/Dockerfile
    image: odm-decisionrunner:8.8.1.1
    links:
    - dbserver
    depends_on:
    - dbserver
    - decisionserverconsole
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    ports:
    - 9070:9080

  decisioncenter:
    build: 
      context: ../
      dockerfile: ./docker-compose/decisioncenter/Dockerfile
    image: odm-decisioncenter:8.8.1.1
    links:
    - dbserver
    depends_on:
    - dbserver
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    ports:
    - 9060:9060
    
  decisionserverruntime:
    build:
      context: ../
      dockerfile: ./docker-compose/decisionserverruntime/Dockerfile
    image: odm-decisionserverruntime:8.8.1.1
    links:
    - dbserver
    - decisionserverconsole
    depends_on:
    - dbserver
    - decisionserverconsole
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    ports:
    - 9090:9080
    - 9443
`

- to publish on Bleumix, we dropped all the volumes temporaly.

**Comment by lgrateau** [comment]
Hi Lionel thanks for this feedback.
I have rename the repository. Need to continue the others items.

**Comment by lgrateau** [comment]
Implement all the requests. The compose is configurable now.
